name: Ubuntu build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bash-completion git meson liblua5.2-dev libglib2.0-dev

    - name: Build
      run: |
        meson setup build --prefix $HOME/opt/tio
        meson compile -C build --verbose
        meson install -C build
